---
version: "2.1"
services:
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - URL=thelinuxtrainer.com
      - VALIDATION=http
      - SUBDOMAINS=vroom, vroomadm, p2p, c2c, bro #optional
      - CERTPROVIDER= #optional
      - PROPAGATION= #optional
      - EMAIL=thegnulinuxtrainer@gmail.com#optionalvchat
      - ONLY_SUBDOMAINS=true #optional
      - EXTRA_DOMAINS= #optional
      - STAGING=false #optional
    volumes:
      - ./appdata/config:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
    networks:
        swag-network:
          aliases:
            - swag
networks:
  swag-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-swag
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: ${IPV4_NETWORK:-172.22.1}.0/24
        - subnet: ${IPV6_NETWORK:-fd4d:6169:6c63:6f77::/64}
    
